language: python
python:
  - "3.6"
services:
  - docker
install:
  - pip install codecov
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
before_install:
  - docker-compose up -d
env:
  global:
     - MATERIALIZATION_POSTGRES_URI=postgres://postgres:synapsedb@localhost:5432/postgres
# command to run tests
script:
  - python setup.py pytest # or py.test for Python versions 3.5 and below
cache:   
  pip: true                                                                    
