version: '3.2'
services:
    db:
      image: mdillon/postgis
      env_file:
        - ./.env.dev   
      ports:
        - 5432:5432
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./entrypoint.sh:/var/lib/postgresql/entrypoint.sh
      healthcheck:
        test: "pg_isready -h localhost -p 5432 -q -U postgres"
        interval: 3s
        timeout: 10s
        retries: 5
    adminer:
      image: adminer
      ports:
        - 8080:8080
      depends_on:
      - db
    redis:
      image: redis:6.0
      container_name: redis
      hostname: redis
      command: ["redis-server"]
      ports:
        - 6379:6379
    celery-process:
      image: 'materialize:tag'
      env_file:
        - ./.env.dev   
      command: ["celery", "worker", "--app=run.celery","--pool=prefork", "--hostname=worker.process@%h", "--queues=process", "--loglevel=INFO", "-Ofair"]
      volumes:
        - ~/.cloudvolume/secrets:/home/nginx/.cloudvolume/secrets:z
      depends_on:
        - redis
    materialize:
      image: 'materialize:tag'
      build:
        context: .
        dockerfile: Dockerfile_Dev
      ports:
        - 80:80
      volumes:
        - ~/.cloudvolume/secrets:/home/nginx/.cloudvolume/secrets:z
        - .:/app
      env_file:
        - ./.env.dev 
      depends_on:
        - db
        - redis
        - celery-process
    flower:
      image: mher/flower
      environment:
        - FLOWER_PORT=5555
      command: ["flower", "--broker=redis://redis:6379/0", "--port=5555"]  
      ports:
        - 5555:5555
      depends_on: 
        - celery-process

volumes:
  postgres_data:
  redis: