services:
  db:
    image: postgis/postgis:13-3.3
    shm_size: 1g
    env_file:
      - ./dev.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./entrypoint.sh:/var/lib/postgresql/entrypoint.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 10s
      retries: 5

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  redis-master:
    image: redis:6.0
    container_name: redis-master
    hostname: redis-master
    command: [ "redis-server" ]
    ports:
      - 6379:6379

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis-master:6379
    ports:
      - 8081:8081
    depends_on:
      - redis-master

  celery-workflow:
    image: 'materialize:tag'
    env_file:
      - ./dev.env
    environment:
      - WORKER_NAME=worker.workflow
      - QUEUE_NAME=workflow
    command: celery --app="run.celery" worker --pool=prefork --hostname=worker.workflow@%h --queues=workflow,celery --concurrency=2 --loglevel=INFO -Ofair
    volumes:
      - ~/.cloudvolume/secrets:/home/nginx/.cloudvolume/secrets:z
      - ~/.cloudvolume/secrets/google-secret.json:/home/nginx/.cloudvolume/secrets/google-secret.json:z
    depends_on:
      - redis-master

  celery-process:
    image: 'materialize:tag'
    env_file:
      - ./dev.env
    environment:
      - WORKER_NAME=worker.process
      - QUEUE_NAME=process
    command: celery --app="run.celery" worker --pool=prefork --hostname=worker.process@%h --queues=celery,process --concurrency=1 --loglevel=INFO -Ofair
    volumes:
      - ~/.cloudvolume/secrets:/home/nginx/.cloudvolume/secrets:z
      - ~/.cloudvolume/secrets/google-secret.json:/home/nginx/.cloudvolume/secrets/google-secret.json:z
    depends_on:
      - redis-master

  celery-beat:
    image: 'materialize:tag'
    env_file:
      - ./dev.env
    command: celery --app=run.celery beat --pidfile=/home/nginx/celerybeat.pid
    volumes:
      - ~/.cloudvolume/secrets:/home/nginx/.cloudvolume/secrets:z
      - ~/.cloudvolume/secrets/google-secret.json:/home/nginx/.cloudvolume/secrets/google-secret.json:z
    depends_on:
      - redis-master

  materialize:
    image: 'materialize:tag'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ~/.cloudvolume/secrets:/home/nginx/.cloudvolume/secrets:z
      - ~/.cloudvolume/secrets/google-secret.json:/home/nginx/.cloudvolume/secrets/google-secret.json:z
      - .:/app
    env_file:
      - ./dev.env
      - ./.env
    depends_on:
      - db
      - redis-master
      - celery-process
      - celery-workflow
      - celery-beat

  flower:
    image: mher/flower:latest
    environment:
      - FLOWER_PORT=5555
    command: celery --broker=redis://redis-master:6379/0 flower --port=5555

    ports:
      - 5555:5555
    depends_on:
      - celery-process
      - celery-workflow

volumes:
  postgres_data:
  redis:
