# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Materialization Engine

on:
  push:
    branches:
      - master
    paths:
      - "materializationengine/**"
      - "tests/**"
      - "requirements.txt"
      - ".github/workflows/**"
  pull_request:
    branches: master

jobs:
  test:
    name: Test against different Python versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/test_requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
     